export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

// CAR
export const GET_ALL_CAR = 'GET_ALL_CAR'
export const GET_ALL_CAR_SUCCESS = 'GET_ALL_CAR_SUCCESS'
export const GET_ALL_CAR_FAILED = 'GET_ALL_CAR_FAILED'

export const DELETE_BY_ID_CAR = 'DELETE_BY_ID_CAR'
export const DELETE_BY_ID_CAR_SUCCESS = 'DELETE_BY_ID_CAR_SUCCESS'
export const DELETE_BY_ID_CAR_FAILED = 'DELETE_BY_ID_CAR_FAILED'

export const INSRT_NEW_CAR = 'INSRT_NEW_CAR'
export const INSRT_NEW_CAR_SUCCESS = 'INSRT_NEW_CAR_SUCCESS'
export const INSRT_NEW_CAR_FAILED = 'INSRT_NEW_CAR_FAILED'

export const UPDATE_CAR = 'UPDATE_CAR'
export const UPDATE_CAR_SUCCESS = 'UPDATE_CAR_SUCCESS'
export const UPDATE_CAR_FAILED = 'UPDATE_CAR_FAILED'
// EMPLOYEE
export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE'
export const GET_ALL_EMPLOYEE_SUCCESS = 'GET_ALL_EMPLOYEE_SUCCESS'
export const GET_ALL_EMPLOYEE_FAILED = 'GET_ALL_EMPLOYEE_FAILED'

export const DELETE_BY_ID_EMPLOYEE = 'DELETE_BY_ID_EMPLOYEE'
export const DELETE_BY_ID_EMPLOYEE_SUCCESS = 'DELETE_BY_ID_EMPLOYEE_SUCCESS'
export const DELETE_BY_ID_EMPLOYEE_FAILED = 'DELETE_BY_ID_EMPLOYEE_FAILED'

export const INSRT_NEW_EMPLOYEE = 'INSRT_NEW_EMPLOYEE'
export const INSRT_NEW_EMPLOYEE_SUCCESS = 'INSRT_NEW_EMPLOYEE_SUCCESS'
export const INSRT_NEW_EMPLOYEE_FAILED = 'INSRT_NEW_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS'
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED'

// SUPPLIER
export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER'
export const GET_ALL_SUPPLIER_SUCCESS = 'GET_ALL_SUPPLIER_SUCCESS'
export const GET_ALL_SUPPLIER_FAILED = 'GET_ALL_SUPPLIER_FAILED'

export const DELETE_BY_ID_SUPPLIER = 'DELETE_BY_ID_SUPPLIER'
export const DELETE_BY_ID_SUPPLIER_SUCCESS = 'DELETE_BY_ID_SUPPLIER_SUCCESS'
export const DELETE_BY_ID_SUPPLIER_FAILED = 'DELETE_BY_ID_SUPPLIER_FAILED'

export const INSRT_NEW_SUPPLIER = 'INSRT_NEW_SUPPLIER'
export const INSRT_NEW_SUPPLIER_SUCCESS = 'INSRT_NEW_SUPPLIER_SUCCESS'
export const INSRT_NEW_SUPPLIER_FAILED = 'INSRT_NEW_SUPPLIER_FAILED'

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER'
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS'
export const UPDATE_SUPPLIER_FAILED = 'UPDATE_SUPPLIER_FAILED'

// OIL

export const GET_ALL_OIL = 'GET_ALL_OIL'
export const GET_ALL_OIL_SUCCESS = 'GET_ALL_OIL_SUCCESS'
export const GET_ALL_OIL_FAILED = 'GET_ALL_OIL_FAILED'

export const DELETE_BY_ID_OIL = 'DELETE_BY_ID_OIL'
export const DELETE_BY_ID_OIL_SUCCESS = 'DELETE_BY_ID_OIL_SUCCESS'
export const DELETE_BY_ID_OIL_FAILED = 'DELETE_BY_ID_OIL_FAILED'

export const INSRT_NEW_OIL = 'INSRT_NEW_OIL'
export const INSRT_NEW_OIL_SUCCESS = 'INSRT_NEW_OIL_SUCCESS'
export const INSRT_NEW_OIL_FAILED = 'INSRT_NEW_OIL_FAILED'

export const UPDATE_OIL = 'UPDATE_OIL'
export const UPDATE_OIL_SUCCESS = 'UPDATE_OIL_SUCCESS'
export const UPDATE_OIL_FAILED = 'UPDATE_OIL_FAILED'

export const GET_ALL_OIL_BY_ID_SUPPLIER = 'GET_ALL_OIL_BY_ID_SUPPLIER'
export const GET_ALL_OIL_BY_ID_SUPPLIER_SUCCESS = 'GET_ALL_OIL_BY_ID_SUPPLIER_SUCCESS'
export const GET_ALL_OIL_BY_ID_SUPPLIER_FAILED = 'GET_ALL_OIL_BY_ID_SUPPLIER_FAILED'

// CUSTOMERS
export const GET_ALL_CUSTOMERS = 'GET_ALL_CUSTOMERS'
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS'
export const GET_ALL_CUSTOMERS_FAILED = 'GET_ALL_CUSTOMERS_FAILED'

export const DELETE_BY_ID_CUSTOMERS = 'DELETE_BY_ID_CUSTOMERS'
export const DELETE_BY_ID_CUSTOMERS_SUCCESS = 'DELETE_BY_ID_CUSTOMERS_SUCCESS'
export const DELETE_BY_ID_CUSTOMERS_FAILED = 'DELETE_BY_ID_CUSTOMERS_FAILED'

export const INSRT_NEW_CUSTOMERS = 'INSRT_NEW_CUSTOMERS'
export const INSRT_NEW_CUSTOMERS_SUCCESS = 'INSRT_NEW_CUSTOMERS_SUCCESS'
export const INSRT_NEW_CUSTOMERS_FAILED = 'INSRT_NEW_CUSTOMERS_FAILED'

export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS'
export const UPDATE_CUSTOMERS_SUCCESS = 'UPDATE_CUSTOMERS_SUCCESS'
export const UPDATE_CUSTOMERS_FAILED = 'UPDATE_CUSTOMERS_FAILED'


// USERS
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'

export const DELETE_BY_ID_USERS = 'DELETE_BY_ID_USERS'
export const DELETE_BY_ID_USERS_SUCCESS = 'DELETE_BY_ID_USERS_SUCCESS'
export const DELETE_BY_ID_USERS_FAILED = 'DELETE_BY_ID_USERS_FAILED'

export const INSRT_NEW_USERS = 'INSRT_NEW_USERS'
export const INSRT_NEW_USERS_SUCCESS = 'INSRT_NEW_USERS_SUCCESS'
export const INSRT_NEW_USERS_FAILED = 'INSRT_NEW_USERS_FAILED'

export const UPDATE_USERS = 'UPDATE_USERS'
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS'
export const UPDATE_USERS_FAILED = 'UPDATE_USERS_FAILED'

// DOCUMENT
export const GET_ALL_DOCUMENT = 'GET_ALL_DOCUMENT'
export const GET_ALL_DOCUMENT_SUCCESS = 'GET_ALL_DOCUMENT_SUCCESS'
export const GET_ALL_DOCUMENT_FAILED = 'GET_ALL_DOCUMENT_FAILED'

export const DELETE_BY_ID_DOCUMENT = 'DELETE_BY_ID_DOCUMENT'
export const DELETE_BY_ID_DOCUMENT_SUCCESS = 'DELETE_BY_ID_DOCUMENT_SUCCESS'
export const DELETE_BY_ID_DOCUMENT_FAILED = 'DELETE_BY_ID_DOCUMENT_FAILED'

export const INSRT_NEW_DOCUMENT = 'INSRT_NEW_DOCUMENT'
export const INSRT_NEW_DOCUMENT_SUCCESS = 'INSRT_NEW_DOCUMENT_SUCCESS'
export const INSRT_NEW_DOCUMENT_FAILED = 'INSRT_NEW_DOCUMENT_FAILED'

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS'
export const UPDATE_DOCUMENT_FAILED = 'UPDATE_DOCUMENT_FAILED'

// ORDER
export const GET_ALL_ORDER = 'GET_ALL_ORDER'
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS'
export const GET_ALL_ORDER_FAILED = 'GET_ALL_ORDER_FAILED'

export const DELETE_BY_ID_ORDER = 'DELETE_BY_ID_ORDER'
export const DELETE_BY_ID_ORDER_SUCCESS = 'DELETE_BY_ID_ORDER_SUCCESS'
export const DELETE_BY_ID_ORDER_FAILED = 'DELETE_BY_ID_ORDER_FAILED'

export const INSRT_NEW_ORDER = 'INSRT_NEW_ORDER'
export const INSRT_NEW_ORDER_SUCCESS = 'INSRT_NEW_ORDER_SUCCESS'
export const INSRT_NEW_ORDER_FAILED = 'INSRT_NEW_ORDER_FAILED'

export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILED = 'UPDATE_ORDER_FAILED'



// TRANSPORTS
export const GET_ALL_TRANSPORTS = 'GET_ALL_TRANSPORTS'
export const GET_ALL_TRANSPORTS_SUCCESS = 'GET_ALL_TRANSPORTS_SUCCESS'
export const GET_ALL_TRANSPORTS_FAILED = 'GET_ALL_TRANSPORTS_FAILED'

export const DELETE_BY_ID_TRANSPORTS = 'DELETE_BY_ID_TRANSPORTS'
export const DELETE_BY_ID_TRANSPORTS_SUCCESS = 'DELETE_BY_ID_TRANSPORTS_SUCCESS'
export const DELETE_BY_ID_TRANSPORTS_FAILED = 'DELETE_BY_ID_TRANSPORTS_FAILED'

export const INSRT_NEW_TRANSPORTS = 'INSRT_NEW_TRANSPORTS'
export const INSRT_NEW_TRANSPORTS_SUCCESS = 'INSRT_NEW_TRANSPORTS_SUCCESS'
export const INSRT_NEW_TRANSPORTS_FAILED = 'INSRT_NEW_TRANSPORTS_FAILED'

export const UPDATE_TRANSPORTS = 'UPDATE_TRANSPORTS'
export const UPDATE_TRANSPORTS_SUCCESS = 'UPDATE_TRANSPORTS_SUCCESS'
export const UPDATE_TRANSPORTS_FAILED = 'UPDATE_TRANSPORTS_FAILED'

//SELL

export const INSRT_NEW_SELL = 'INSRT_NEW_SELL'
export const INSRT_NEW_SELL_SUCCESS = 'INSRT_NEW_SELL_SUCCESS'
export const INSRT_NEW_SELL_FAILED = 'INSRT_NEW_SELL_FAILED'

export const GET_MAX_ID_SELL = 'GET_MAX_ID_SELL'
export const GET_MAX_ID_SELL_SUCCESS = 'GET_MAX_ID_SELL_SUCCESS'
export const GET_MAX_ID_SELL_FAILED = 'GET_MAX_ID_SELL_FAILED'

export const INSRT_NEW_SELL_DETAIL = 'INSRT_NEW_SELL_DETAIL'
export const INSRT_NEW_SELL_DETAIL_SUCCESS = 'INSRT_NEW_SELL_DETAIL_SUCCESS'
export const INSRT_NEW_SELL_DETAIL_FAILED = 'INSRT_NEW_SELL_DETAIL_FAILED'


export const GET_MAX_ID_ORDER = 'GET_MAX_ID_ORDER'
export const GET_MAX_ID_ORDER_SUCCESS = 'GET_MAX_ID_ORDER_SUCCESS'
export const GET_MAX_ID_ORDER_FAILED = 'GET_MAX_ID_ORDER_FAILED'

export const INSRT_NEW_ORDER_DETAIL = 'INSRT_NEW_ORDER_DETAIL'
export const INSRT_NEW_ORDER_DETAIL_SUCCESS = 'INSRT_NEW_ORDER_DETAIL_SUCCESS'
export const INSRT_NEW_ORDER_DETAIL_FAILED = 'INSRT_NEW_ORDER_DETAIL_FAILED'

export const GET_SEARCH_ORDER = 'GET_SEARCH_ORDER'
export const GET_SEARCH_ORDER_SUCCESS = 'GET_SEARCH_ORDER_SUCCESS'
export const GET_SEARCH_ORDER_FAILED = 'GET_SEARCH_ORDER_FAILED'

export const INSRT_NEW_IMPORT = 'INSRT_NEW_IMPORT'
export const INSRT_NEW_IMPORT_SUCCESS = 'INSRT_NEW_IMPORT_SUCCESS'
export const INSRT_NEW_IMPORT_FAILED = 'INSRT_NEW_IMPORT_FAILED'

export const GET_MAX_ID_IMPORT = 'GET_MAX_ID_IMPORT'
export const GET_MAX_ID_IMPORT_SUCCESS = 'GET_MAX_ID_IMPORT_SUCCESS'
export const GET_MAX_ID_IMPORT_FAILED = 'GET_MAX_ID_IMPORT_FAILED'

export const INSRT_NEW_IMPORT_DETAIL = 'INSRT_NEW_IMPORT_DETAIL'
export const INSRT_NEW_IMPORT_DETAIL_SUCCESS = 'INSRT_NEW_IMPORT_DETAIL_SUCCESS'
export const INSRT_NEW_IMPORT_DETAIL_FAILED = 'INSRT_NEW_IMPORT_DETAIL_FAILED'


export const GET_ALL_REPORT = 'GET_ALL_REPORT'
export const GET_ALL_REPORT_SUCCESS = 'GET_ALL_REPORT_SUCCESS'
export const GET_ALL_REPORT_FAILED = 'GET_ALL_REPORT_FAILED'


export const GET_SUM_REPORT = 'GET_SUM_REPORT'
export const GET_SUM_REPORT_SUCCESS = 'GET_SUM_REPORT_SUCCESS'
export const GET_SUM_REPORT_FAILED = 'GET_SUM_REPORT_FAILED'


export const GET_ALL_SELL = 'GET_ALL_SELL'
export const GET_ALL_SELL_SUCCESS = 'GET_ALL_SELL_SUCCESS'
export const GET_ALL_SELL_FAILED = 'GET_ALL_SELL_FAILED'

export const GET_PRINT_SELL = 'GET_PRINT_SELL'
export const GET_PRINT_SELL_SUCCESS = 'GET_PRINT_SELL_SUCCESS'
export const GET_PRINT_SELL_FAILED = 'GET_PRINT_SELL_FAILED'

export const GET_PRINT_ORDER = 'GET_PRINT_ORDER'
export const GET_PRINT_ORDER_SUCCESS = 'GET_PRINT_ORDER_SUCCESS'
export const GET_PRINT_ORDER_FAILED = 'GET_PRINT_ORDER_FAILED'

export const GET_PRINT_IMPORT = 'GET_PRINT_IMPORT'
export const GET_PRINT_IMPORT_SUCCESS = 'GET_PRINT_IMPORT_SUCCESS'
export const GET_PRINT_IMPORT_FAILED = 'GET_PRINT_IMPORT_FAILED'

export const GET_ALL_DOCUMENT_BY_ID = 'GET_ALL_DOCUMENT_BY_ID'
export const GET_ALL_DOCUMENT_BY_ID_SUCCESS = 'GET_ALL_DOCUMENT_BY_ID_SUCCESS'
export const GET_ALL_DOCUMENT_BY_ID_FAILED = 'GET_ALL_DOCUMENT_BY_ID_FAILED'

export const GET_ALL_TRANSPORTS_BY_ID = 'GET_ALL_TRANSPORTS_BY_ID'
export const GET_ALL_TRANSPORTS_BY_ID_SUCCESS = 'GET_ALL_TRANSPORTS_BY_ID_SUCCESS'
export const GET_ALL_TRANSPORTS_BY_ID_FAILED = 'GET_ALL_TRANSPORTS_BY_ID_FAILED'